# data.rb

FREEZER = Location.new('freezer')
DRAWERS = Location.new('drawers', 'You are now in the drawers!')
SINK = Location.new('sink', 'You are in the sink - don\'t get washed down!')
COUNTER = Location.new('counter', 'You made it up to the counter! You are now on top of kitchen world, looking down on... wait')
MICROWAVE = Location.new('microwave')
FLOOR = Location.new('floor', 'Don\'t they sweep the floor around here?')
CUPBOARD = Location.new('cupboard')
CHICKEN_SCRAPS = Location.new('chicken_scraps')
TRASHBIN = Location.new('trashbin', 'You are in the trash bin... eww')
RECYCLING = Location.new('recycling', 'You made it to the recycling!')
PORTABLE_BANANA_HOLDER = Location.new('portable_banana_holder')
TOASTER =  Location.new('toaster')
KNIFE_RACK =  Location.new('knife_rack')
GARBAGE_DISPOSAL =  Location.new('garbage_disposal')
STOVE =  Location.new('stove')
FRIDGE =  Location.new('fridge')

TRASHBIN.add_direction("right", RECYCLING)
RECYCLING.add_direction('right', DRAWERS)
RECYCLING.add_direction('left', TRASHBIN)
DRAWERS.add_direction('down', FLOOR)
DRAWERS.add_direction('up', COUNTER)
DRAWERS.add_direction('left', RECYCLING)
FLOOR.add_direction('up', DRAWERS)
COUNTER.add_direction('down', DRAWERS)
COUNTER.add_direction('up', TOASTER)
COUNTER.add_direction('left', STOVE)
COUNTER.add_direction('right', SINK)
TOASTER.add_direction('down', COUNTER)
SINK.add_direction('left', COUNTER)
SINK.add_direction('up', PORTABLE_BANANA_HOLDER)
SINK.add_direction('down', GARBAGE_DISPOSAL)
SINK.add_direction('right', CHICKEN_SCRAPS)
PORTABLE_BANANA_HOLDER.add_direction('down', SINK)
CHICKEN_SCRAPS.add_direction('left', SINK)
